server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false  # false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己是注册中心，职责是维护服务实例，不需要检索服务
    service-url:  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖的这个地址。
#      defaultZone: http://eureka7002.com:7002/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/  #单机版
  server:
    enable-self-preservation: false # 关闭自我保护机制，保证不可用服务即使剔除
    eviction-interval-timer-in-ms: 2000 #清理间隔