server:
  port: 80

spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接后从服务器读取可用资源所用的时间
  ReadTimeout:  5000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以debug级别监控下面这个接口，并打印出全部日志信息
    com.xiaolun.service.PaymentFeignService: debug
